Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,11 +19,7 @@ jobs:
           port: ${{ secrets.GHACTIONS_PORT }}
           script: |
             set -e  # Detener el script si ocurre un error
-            echo "Iniciando comandos remotos"
-            echo "Directorio de trabajo: ${{ secrets.GHACTIONS_WORK_DIR }}"
-            echo "Rama: ${{ secrets.GHACTIONS_BRANCH }}"
             cd ${{ secrets.GHACTIONS_WORK_DIR }}
-            git fetch || { echo "Error: git fetch falló"; exit 1; }
-            git checkout ${{ secrets.GHACTIONS_BRANCH }} || { echo "Error: git checkout falló"; exit 1; }
-            git pull || { echo "Error: git pull falló"; exit 1; }
-            echo "Proceso completado con éxito"
+            git reset --hard
+            git pull origin ${{ secrets.GHACTIONS_BRANCH }} || { echo "Error: git pull falló"; exit 1; }
+            echo "Repositorio sincronizado correctamente"
